name: CI/CD Pipeline

on:
  push:
    branches:
    - dev
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ github.event_name == 'push' && contains(github.event.ref, 'master')  && 'datsproject-io' || 'datsproject-io-dev' }}
      NAMESPACE: default
      KUBECONFIG_CONTENT: ${{ github.event_name == 'push' && contains(github.event.ref, 'master')  && secrets.KUBECONFIG || secrets.KUBECONFIG_DEV }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.NEXUS_URL }}
        username: ${{ secrets.NEXUS_USERNAME }}
        password: ${{ secrets.NEXUS_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.NEXUS_URL }}/${{ env.IMAGE_NAME }}:v${{ github.run_number }}

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3

    - name: Set up Helm
      uses: azure/setup-helm@v2

    - name: Deploy to Kubernetes using Helm
      run: |
        # kubeconfig and test 
        echo "$KUBECONFIG_CONTENT" > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig
        kubectl cluster-info

        # deploy k8s
        helm upgrade --install ${{ env.IMAGE_NAME }} ./helm --set image.repository=${{ secrets.NEXUS_URL }}/${{ env.IMAGE_NAME }} --set image.tag=v${{ github.run_number }} --namespace ${{ env.NAMESPACE }} --wait --kubeconfig=$KUBECONFIG
